require File.expand_path(File.join(File.dirname(__FILE__), *%w[app models article]))
require File.expand_path(File.join(File.dirname(__FILE__), *%w[app controllers articles_controller]))
require File.expand_path(File.join(File.dirname(__FILE__), *%w[app controllers admin_controller]))
require File.expand_path(File.join(File.dirname(__FILE__), *%w[app controllers admin articles_controller]))
require File.expand_path(File.join(File.dirname(__FILE__), *%w[app helpers articles_helper]))
